aftershock_interval: 60
agents:
- battery: 100
  id: medic1
  kind: medic
  pos:
  - 2
  - 3
- battery: 100
  id: medic2
  kind: medic
  pos:
  - 3
  - 2
- id: truck1
  kind: truck
  pos:
  - 1
  - 3
  tools: 3
  water: 5
- id: truck2
  kind: truck
  pos:
  - 3
  - 1
  tools: 3
  water: 5
- battery: 100
  id: drone1
  kind: drone
  pos:
  - 1
  - 1
depot:
- 2
- 2
height: 25
hospitals:
- capacity: 4
  pos:
  - 22
  - 22
initial_fires:
- - 7
  - 7
- - 12
  - 12
- - 17
  - 17
rubble:
- - 6
  - 10
- - 14
  - 8
- - 16
  - 14
- - 10
  - 18
survivors:
- deadline: 150
  id: 1
  pos:
  - 5
  - 5
- deadline: 120
  id: 2
  pos:
  - 10
  - 15
- deadline: 180
  id: 3
  pos:
  - 15
  - 5
- deadline: 90
  id: 4
  pos:
  - 20
  - 10
- deadline: 200
  id: 5
  pos:
  - 8
  - 20
- deadline: 160
  id: 6
  pos:
  - 18
  - 18
width: 25
