aftershock_interval: 60
agents:
- battery: 100
  id: medic1
  kind: medic
  pos:
  - 1
  - 2
- battery: 100
  id: medic2
  kind: medic
  pos:
  - 2
  - 1
- id: truck1
  kind: truck
  pos:
  - 1
  - 3
  tools: 3
  water: 5
- battery: 100
  id: drone1
  kind: drone
  pos:
  - 2
  - 2
depot:
- 1
- 1
height: 20
hospitals:
- capacity: 3
  pos:
  - 17
  - 2
- capacity: 3
  pos:
  - 15
  - 15
initial_fires:
- - 8
  - 3
- - 12
  - 12
rubble:
- - 7
  - 7
- - 7
  - 8
- - 8
  - 7
survivors:
- deadline: 150
  id: 1
  pos:
  - 2
  - 2
- deadline: 120
  id: 2
  pos:
  - 3
  - 14
- deadline: 180
  id: 3
  pos:
  - 4
  - 9
- deadline: 90
  id: 4
  pos:
  - 6
  - 3
- deadline: 200
  id: 5
  pos:
  - 7
  - 15
width: 20
