aftershock_interval: 45
agents:
- battery: 100
  id: medic1
  kind: medic
  pos:
  - 2
  - 3
- battery: 100
  id: medic2
  kind: medic
  pos:
  - 3
  - 2
- battery: 100
  id: medic3
  kind: medic
  pos:
  - 1
  - 4
- id: truck1
  kind: truck
  pos:
  - 1
  - 3
  tools: 3
  water: 5
- id: truck2
  kind: truck
  pos:
  - 3
  - 1
  tools: 3
  water: 5
- battery: 100
  id: drone1
  kind: drone
  pos:
  - 1
  - 1
- battery: 100
  id: drone2
  kind: drone
  pos:
  - 4
  - 1
depot:
- 2
- 2
height: 30
hospitals:
- capacity: 3
  pos:
  - 27
  - 27
- capacity: 3
  pos:
  - 27
  - 2
initial_fires:
- - 7
  - 7
- - 12
  - 12
- - 17
  - 17
- - 22
  - 22
- - 10
  - 20
- - 20
  - 10
rubble:
- - 6
  - 10
- - 14
  - 8
- - 16
  - 14
- - 10
  - 18
- - 20
  - 15
- - 15
  - 20
- - 25
  - 12
- - 12
  - 25
survivors:
- deadline: 120
  id: 1
  pos:
  - 5
  - 5
- deadline: 90
  id: 2
  pos:
  - 10
  - 15
- deadline: 150
  id: 3
  pos:
  - 15
  - 5
- deadline: 80
  id: 4
  pos:
  - 20
  - 10
- deadline: 180
  id: 5
  pos:
  - 8
  - 20
- deadline: 130
  id: 6
  pos:
  - 18
  - 18
- deadline: 100
  id: 7
  pos:
  - 25
  - 5
- deadline: 140
  id: 8
  pos:
  - 5
  - 25
- deadline: 110
  id: 9
  pos:
  - 15
  - 25
width: 30
